version: '3.8'

services:
  partybook.microservices.nightclub:
    image: ${DOCKER_REGISTRY-}partybookmicroservicesnightclub
    build:
      context: .
      dockerfile: PartyBook.MicroServices.NightClub/Dockerfile
